### ISSUE TITLE
Attempted to build

### ISSUE THREAD

**Issue by willbishops** [St1rling/GStudent#9]
Hi there, I tried to build this program but it failed.

However that is not my question, the description is not yet added, but just wondering what GStudent is

**Comment by St1rling** [comment]
G'day, it was about time I added the description, so I've uploaded a file I made a while back [here](https://github.com/St1rling/GStudent/blob/master/GStudent.docx). To build you need to extra libraries which I have zipped up and put [here](https://drive.google.com/open?id=0B4HFKb4RO6uWTExJM0p5LU1Zd3M). Thanks for checking out the project :)

**Comment by St1rling** [comment]
The project itself is targeted at Australian schools, and at this stage it is specifically targeted at Glenunga International High School (GIHS).

**Comment by willbishop** [comment]
?Ok, I actually attend that school myself, but I am wondering what is actually does, if you are able to talk about that yet

________________________________

**Comment by St1rling** [comment]
Have you read the document in the repo? "About GStudent.docx"

**Comment by willbishops** [comment]
Sorry, I only got one email from you about it, I found it though. I am having trouble compiling this, not sure how to, to be honest (never used Java before). I assume each there is one main file which I execute which references others? I download the JDK and I am using Sublime Text. I am trying to run GStudent.java which produces 39 errors, which you can read at http://pastebin.com/38xndr8z

**Comment by St1rling** [comment]
It's a bit different, you'll probably want to download an IDE such as IntelliJ to compile it, since it's easier than by hand. If you want compiled versions which you just double click, check out the GStudent Resources repository. I think the newest is GS-D0015, don't use GS-D0116, its pretty broken.

**Comment by willbishops** [comment]
Will do, thank you

**Comment by willbishops** [comment]
I think I'll need to wait until release, GS-D0015 doesn't seem to work properly for me. I get to the signup page, and clicking 'Let's Go!' does nothing. Also, I tried logging in with my Daymap credentials, and it let me log in, despite it not being a real account.

**Comment by St1rling** [comment]
Yeah, I know, it does no checks as it's in Alpha. Its only providing the base ui until I hook the server and client.

**Comment by willbishops** [comment]
Oh so the compiled version does not yet interface with the server? Ok then, I'll try again another time
